language: java
git:
   depth: 3
jobs:
   include:
   -  stage: native-libs
      os: linux
      dist: bionic
      jdk: oraclejdk11
      env: DEPLOY=true
   -  os: osx
      jdk: oraclejdk11
      env: DEPLOY=true
   -  stage: multi-platform
      os: linux
      jdk: oraclejdk11
      env:
      - OPTIONS='-Dmulti-platform -pl !cadical'
      - DEPLOY=true
   -  os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8
      env: OPTIONS='-Dmulti-platform -pl !cadical'
cache:
   directories:
   - $HOME/.m2
before_install: mkdir -p ~/.m2 && cp .settings.xml ~/.m2/settings.xml
install: mvn install -DskipTests=true -U $OPTIONS
script: mvn test -Dassembly.skipAssembly=true -B $OPTIONS -pl '!cadical'
after_success:
- test "$DEPLOY" = true -a "$TRAVIS_PULL_REQUEST" = false && mvn source:jar deploy -DskipTests=true -B $OPTIONS